### ISSUE TITLE
Shipping app with database data

### ISSUE THREAD

**Issue by guit4eva** [tekartik/sembast.dart#193]
is it possible to ship an app with prepopulated data? ie, all the data saved to a database during development.

Example data:
```
  'title': 'A book', (String)
  'rating': 4, (int)
  'categories': 'romance, drama', (String)
  'image': 'assets/img/covers/$id_cover.jpg' (String)
```

**Comment by alextekartik** [comment]
I think the safest would be to:
* export your database - [`exportDatabase`](https://pub.dev/documentation/sembast/latest/sembast.utils.sembast_import_export/exportDatabase.html) - during developement when you think your data is read.
* bundle the export in your app (it is a json map)
* on first launch, if the database does not exist, import the data - [`importDatabase`](https://pub.dev/documentation/sembast/latest/sembast.utils.sembast_import_export/importDatabase.html) - to create a new database

**Comment by guit4eva** [comment]
> I think the safest would be to:
> 
> * export your database - [`exportDatabase`](https://pub.dev/documentation/sembast/latest/sembast.utils.sembast_import_export/exportDatabase.html) - during developement when you think your data is read.
> * bundle the export in your app (it is a json map)
> * on first launch, if the database does not exist, import the data - [`importDatabase`](https://pub.dev/documentation/sembast/latest/sembast.utils.sembast_import_export/importDatabase.html) - to create a new database

Thanks very much for that, greatly appreciated. I'm close (I think), but I'm battling to get this to work smoothly. Basically, I want to import a fresh copy of the database every time the app loads. The app on mobile seems to load the fresh database if I force close and open again. Otherwise it hangs on loading. This is my code so far, not sure where I'm going wrong:

```
class AppDatabase {
  static final AppDatabase _singleton = AppDatabase._();

  static AppDatabase get instance => _singleton;

  // Completer is used for transforming synchronous code into asynchronous code.
  Completer<Database> _dbOpenCompleter;

  // A private constructor. Allows us to create instances of AppDatabase
  // only from within the AppDatabase class itself.
  AppDatabase._();

  // Database object accessor
  Future<Database> get database async {
    // If completer is null, AppDatabaseClass is newly instantiated, so database is not yet opened
    if (_dbOpenCompleter == null) {
      _dbOpenCompleter = Completer();
      // Calling _openDatabase will also complete the completer with database instance
      _openDatabase();
    }
    // If the database is already opened, awaiting the future will happen instantly.
    // Otherwise, awaiting the returned future will take some time - until complete() is called
    // on the Completer in _openDatabase() below.
    return _dbOpenCompleter.future;
  }

  Future initialImportDatabase(factory, dbPath) async {
    var _theDb = await rootBundle.loadString('assets/json/db.json');
    var _theJson = await jsonDecode(_theDb);

    await importDatabase(_theJson, factory, dbPath);
  }

  Future _openDatabase() async {
    if (kIsWeb) {
      final _dbPath = 'books.db';
      // Import fresh copy of database
      await initialImportDatabase(databaseFactoryWeb, _dbPath);
      // Open the database
      final database = await databaseFactoryWeb.openDatabase(_dbPath);

      _dbOpenCompleter.complete(database);
    } else {
      // Get a platform-specific directory where persistent app data can be stored
      final appDocumentDir = await getApplicationDocumentsDirectory();
      final _dbPath = join(appDocumentDir.path, 'books.db');
      // Import fresh copy of database
      await initialImportDatabase(databaseFactoryIo, _dbPath);
      // Open the database
      final database = await databaseFactoryIo.openDatabase(_dbPath);

      // Any code awaiting the Completer's future will now start executing
      _dbOpenCompleter.complete(database);
    }
  }
}
```

**Comment by alextekartik** [comment]
`importDatabase` returns the open database. no need to open it. You should try something like that:

```dart
/// Returns the opened database
Future<Database> initialImportDatabase(factory, dbPath) async {
  var _theDb = await rootBundle.loadString('assets/json/db.json');
  var _theJson = await jsonDecode(_theDb);

  return await importDatabase(_theJson, factory, dbPath);
}

...

// Import fresh copy of database
var database = await initialImportDatabase(databaseFactoryWeb, _dbPath);
_dbOpenCompleter.complete(database);
```

**Comment by guit4eva** [comment]
Ah ok! That makes sense. However, after removing the openDatabase line, it's still hanging on loading with the following error:

```
RangeError: Maximum call stack size exceeded
at _Future.new.[_prependListeners] (http://localhost:56914/dart_sdk.js:32447:30)
at _Future.new.[_prependListeners] (http://localhost:56914/dart_sdk.js:32447:30)
at _Future.new.[_prependListeners] (http://localhost:56914/dart_sdk.js:32447:30)
at _Future.new.[_prependListeners] (http://localhost:56914/dart_sdk.js:32447:30)
at _Future.new.[_prependListeners] (http://localhost:56914/dart_sdk.js:32447:30)
...
...
...
at Function._chainCoreFuture (http://localhost:56914/dart_sdk.js:32520:36)
    at _Future.new.[_chainFuture] (http://localhost:56914/dart_sdk.js:32578:27)
    at _Future.new.[_asyncComplete] (http://localhost:56914/dart_sdk.js:32558:29)
    at _AsyncCompleter.new.complete (http://localhost:56914/dart_sdk.js:32010:36)
    at database_setup.AppDatabase.__._openDatabase (http://localhost:56914/packages/localis_stay/services/database_setup.dart.lib.js:51:34)
    at _openDatabase.next (<anonymous>)
```

**Comment by alextekartik** [comment]
If you can attach your export or send it to me (alex@tekartik.com), I can take a look.

**Comment by guit4eva** [comment]
> If you can attach your export or send it to me ([alex@tekartik.com](mailto:alex@tekartik.com)), I can take a look.

Thanks so much! Here is the export:

```
{
    "sembast_export": 1,
    "version": 1,
    "stores": [
        {
            "name": "Books",
            "keys": [
                "22b56785-129b-4d59-b334-d5374719f19a"
            ],
            "values": [
                {
                    "id": "22b56785-129b-4d59-b334-d5374719f19a",
                    "shortId": "22b56",
                    "title": "Test Book",
                    "category": [
                        "drama"
                    ]
                }
            ]
        }
    ]
}
```

**Comment by alextekartik** [comment]
Sorry i don't see anything wrong the export. not sure if this is sembast related though since it seems to happen after the import, and hard to tell without debugging at this point...

**Comment by 926** [comment]
@guit4eva I don't know if this will do it for you, but declaring json base objects in the .main worked for us : 
https://github.com/926/come_share/blob/master/lib/main.dart

Here is the web demo https://yobi2-skvwz.mongodbstitch.com/#/flocks

I presume data is stored in browser cache,
What would be the right way to remove it ?
