### ISSUE TITLE
Bad state: read only

### ISSUE THREAD

**Issue by vishnuiiit** [tekartik/sembast.dart#206]
I was getting data from sembast database.
And then assigning data to a local variable and modifying that with this code:-
```
var store = intMapStoreFactory.store(playerStoreName);
var map = await store.record(3).get(await db);
map['shares'] = [2, 4];
```

and then I got this error:-
```
E/flutter ( 5205): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Bad state: read only
E/flutter ( 5205): #0      ImmutableMap.[]= (package:sembast/src/utils.dart:342:40)
E/flutter ( 5205): #1      Phone.getPlayers (package:stockexchange/network/offline_database.dart:82:12)
E/flutter ( 5205): <asynchronous suspension>
E/flutter ( 5205): #2      Phone.getGame (package:stockexchange/network/offline_database.dart:38:21)
E/flutter ( 5205): #3      _HomePageState.initState (package:stockexchange/pages/home_page.dart:29:11)
E/flutter ( 5205): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
E/flutter ( 5205): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter ( 5205): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter ( 5205): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 5205): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter ( 5205): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter ( 5205): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter ( 5205): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter ( 5205): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 5205): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter ( 5205): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter ( 5205): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter ( 5205): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter ( 5205): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter ( 5205): #30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter ( 5205): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 5205): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter ( 5205): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter ( 5205): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter ( 5205): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter ( 5205): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter ( 5205): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 5205): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 5205): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter ( 5205): #44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter ( 5205): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 5205): #46     ComponentElement._
```

**Comment by vishnuiiit** [comment]
Sorry got it, from here https://github.com/tekartik/sembast.dart/blob/b1e0823835e55bfa591567df550ce9e6e98f4433/sembast/doc/queries.md#modify-a-read-result
