### ISSUE TITLE
Using Null as a Map key

### ISSUE THREAD

**Issue by LeoBound** [tekartik/sembast.dart#393]
Hi,
Is there some way to allow `null` as the key of a stored Map?
For example if I have some `Map<String, Map<String?, String>>` and try to insert it I get an error.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
#0      cloneValueOrNull.<anonymous closure> (package:sembast/src/utils.dart:266:38)
#1      MapBase.map (dart:collection/maps.dart:82:28)
#2      cloneValueOrNull (package:sembast/src/utils.dart:265:18)
#3      cloneValue.<anonymous closure> (package:sembast/src/utils.dart:254:49)
#4      MapBase.map (dart:collection/maps.dart:82:28)
#5      cloneValue (package:sembast/src/utils.dart:253:18)
#6      SembastStore.txnPutSync (package:sembast/src/store_impl.dart:153:15)
#7      SembastStore.txnAdd (package:sembast/src/store_impl.dart:123:7)
```

I tried to insert it with the following code:
```dart
  await stringMapStoreFactory.store("test").add(refDb, {
    "key": {null: "value"}
  });
```

Thanks

**Comment by alextekartik** [comment]
Any map stored in sembast is assumed (or converted) to be of type `Map<String, Object?>` which disallow null keys (and I think most db would have the same limitation).

At the end the content is encoded a json and json encoding has the same limitation:

```dart
  // Ok
  jsonEncode({'test': 1});
  // Fail
  jsonEncode({null: 1});
```

**Comment by LeoBound** [comment]
Fair enough! Thanks for the quick reply 🙂
