### ISSUE TITLE
Unhandled Exception: Invalid argument(s)

### ISSUE THREAD

**Issue by zubairehman** [tekartik/sembast.dart#44]
Hi,
First of all thank you so much for such a great library. I am getting this exception when i am trying to store my objects in DB. I am using json_serializable package for serialization, but whenever i try to add something in DB it throws an exception. Below are my model classes:

**Sembast Version:**
```dart
  sembast: ^1.16.0+3
```

**Job:**
```dart
import 'package:cubivue_app/models/jobsummary/job_summary.dart';
import 'package:cubivue_app/models/task/task.dart';

import 'package:json_annotation/json_annotation.dart';

/// This allows the `User` class to access private members in
/// the generated file. The value for this is *.g.dart, where
/// the star denotes the source file name.
part 'job.g.dart';

/// An annotation for the code generator to know that this class needs the
/// JSON serialization logic to be generated.
@JsonSerializable(anyMap: true)
class Job {
  String headerSubTitleLeft;
  String headerSubTitleRight;
  String headerTitleLeft;
  String headerTitleRight;
  String jobId;
  String jobTileSubTitle;
  String jobTileTitle;
  JobSummary jobSummary;
  List<Task> tasks;

  Job({
    this.headerSubTitleLeft,
    this.headerSubTitleRight,
    this.headerTitleLeft,
    this.headerTitleRight,
    this.jobId,
    this.jobSummary,
    this.jobTileSubTitle,
    this.jobTileTitle,
    this.tasks,
  });

  /// A necessary factory constructor for creating a new User instance
  /// from a map. Pass the map to the generated `_$UserFromJson()` constructor.
  /// The constructor is named after the source class, in this case User.
  factory Job.fromJson(Map<String, dynamic> json) => _$JobFromJson(json);

  /// `toJson` is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method `_$UserToJson`.
  Map<String, dynamic> toJson() => _$JobToJson(this);
}
```

**Task:**
```dart
import 'package:cubivue_app/models/actions/action.dart';

import 'package:json_annotation/json_annotation.dart';

/// This allows the `User` class to access private members in
/// the generated file. The value for this is *.g.dart, where
/// the star denotes the source file name.
part 'task.g.dart';

/// An annotation for the code generator to know that this class needs the
/// JSON serialization logic to be generated.
@JsonSerializable(anyMap: true)
class Task {
  List<TaskAction> actions;
  String subTitle;
  String taskListId;
  String taskId;
  String title;

  Task({
    this.actions,
    this.subTitle,
    this.taskListId,
    this.taskId,
    this.title,
  });

  /// A necessary factory constructor for creating a new User instance
  /// from a map. Pass the map to the generated `_$UserFromJson()` constructor.
  /// The constructor is named after the source class, in this case User.
  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);

  /// `toJson` is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method `_$UserToJson`.
  Map<String, dynamic> toJson() => _$TaskToJson(this);
}
```

**Job Summary:**
```dart
import 'package:flutter/foundation.dart';

import 'package:json_annotation/json_annotation.dart';

/// This allows the `User` class to access private members in
/// the generated file. The value for this is *.g.dart, where
/// the star denotes the source file name.
part 'job_summary.g.dart';

/// An annotation for the code generator to know that this class needs the
/// JSON serialization logic to be generated.
@JsonSerializable(anyMap: true)
class JobSummary {
  final String date;
  final String name;
  final String phone;
  final String time;

  JobSummary({
    this.date,
    this.name,
    this.phone,
    this.time,
  });

  /// A necessary factory constructor for creating a new User instance
  /// from a map. Pass the map to the generated `_$UserFromJson()` constructor.
  /// The constructor is named after the source class, in this case User.
  factory JobSummary.fromJson(Map<String, dynamic> json) =>
      _$JobSummaryFromJson(json);

  /// `toJson` is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method `_$UserToJson`.
  Map<String, dynamic> toJson() => _$JobSummaryToJson(this);
}
```

**Action:**
```dart

import 'package:json_annotation/json_annotation.dart';

/// This allows the `User` class to access private members in
/// the generated file. The value for this is *.g.dart, where
/// the star denotes the source file name.
part 'action.g.dart';

/// An annotation for the code generator to know that this class needs the
/// JSON serialization logic to be generated.
@JsonSerializable(anyMap: true)
class TaskAction {
  String actionId;
  String actionTypeId;
  String caption;
  bool required;

  TaskAction({
    this.actionId,
    this.actionTypeId,
    this.caption,
    this.required,
  });

  /// A necessary factory constructor for creating a new User instance
  /// from a map. Pass the map to the generated `_$UserFromJson()` constructor.
  /// The constructor is named after the source class, in this case User.
  factory TaskAction.fromJson(Map<String, dynamic> json) => _$TaskActionFromJson(json);

  /// `toJson` is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method `_$UserToJson`.
  Map<String, dynamic> toJson() => _$TaskActionToJson(this);
}
```
I tried converting my json manually and it worked.  The problem occurs only when i use `json_serializable`. Help would be appreciated :) 

**DB Call**
```dart
  Future<int> insert(Job job) async {
    print('[JobDataSource][insert] insert job: ${job.jobId}');
    return await _jobsStore.add(await _db, job.toJson());
  }
```

**Exception:**
```
ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): value Instance of 'JobSummary' unsupported type JobSummary
E/flutter (31372): #0      cloneValue (package:sembast/src/utils.dart:174:3)
E/flutter (31372): #1      cloneValue.<anonymous closure> (package:sembast/src/utils.dart:157:49)
E/flutter (31372): #2      MapMixin.map (dart:collection/maps.dart:163:28)
E/flutter (31372): #3      cloneValue (package:sembast/src/utils.dart:156:18)
E/flutter (31372): #4      makeImmutableRecord (package:sembast/src/record_impl.dart:313:45)
E/flutter (31372): #5      SembastStore.txnPutRecordSync (package:sembast/src/store_impl.dart:449:25)
E/flutter (31372): #6      SembastStore.txnPutSync (package:sembast/src/store_impl.dart:107:14)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #7      SembastStore.txnAdd (package:sembast/src/store_impl.dart:93:19)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #8      _SembastStoreRef&Object&StoreRefMixin.add.<anonymous closure> (package:sembast/src/store_ref_impl.dart:73:12)
E/flutter (31372): #9      SembastDatabase.inTransaction.<anonymous closure> (package:sembast/src/database_impl.dart:1064:34)
E/flutter (31372): #10     SembastDatabase.transaction.<anonymous closure>.<anonymous closure> (package:sembast/src/database_impl.dart:911:57)
E/flutter (31372): #11     new Future.sync (dart:async/future.dart:224:31)
E/flutter (31372): #12     SembastDatabase.transaction.<anonymous closure> (package:sembast/src/database_impl.dart:911:24)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #13     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #14     SembastDatabase.transaction (package:sembast/src/database_impl.dart:897:28)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #15     SembastDatabase.inTransaction (package:sembast/src/database_impl.dart:1064:7)
E/flutter (31372): #16     _SembastStoreRef&Object&StoreRefMixin.add (package:sembast/src/store_ref_impl.dart:69:25)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #17     JobDataSource.insert (package:cubivue_app/data/local/datasources/job/job_datasource.dart:20:29)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #18     JobDataSource.insertMany.<anonymous closure> (package:cubivue_app/data/local/datasources/job/job_datasource.dart:25:34)
E/flutter (31372): #19     List.forEach (dart:core-patch/growable_array.dart:278:8)
E/flutter (31372): #20     JobDataSource.insertMany (package:cubivue_app/data/local/datasources/job/job_datasource.dart:25:17)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #21     Repository.getMyJobs (package:cubivue_app/data/repository.dart:259:10)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #22     _JobStore.getMyJobs (package:cubivue_app/stores/job/job_store.dart:76:17)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #23     JobStore.getMyJobs.<anonymous closure> (package:cubivue_app/stores/job/job_store.g.dart:136:51)
E/flutter (31372): #24     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (31372): #25     _ZoneDelegate.run (dart:async/zone.dart:711:19)
E/flutter (31372): #26     AsyncAction._run (package:mobx/src/api/async/async_action.dart:42:29)
E/flutter (31372): #27     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (31372): #28     AsyncAction.run (package:mobx/src/api/async/async_action.dart:25:26)
E/flutter (31372): <asynchronous suspension>
E/flutter (31372): #29     JobStore.getMyJobs (package:cubivue_app/stores/job/job_store.g.dart:136:35)
E/flutter (31372): #30     _AllJobsScreenState.initState.<anonymous closure> (package:cubivue_app/ui/allJobs/all_jobs.dart:28:18)
E/flutter (31372): #31     new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter (31372): #32     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (31372): #33     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (31372): #34     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (31372): #35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (31372): #36     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (31372): #37     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (31372): #38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (31372): #39     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (31372): #40     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (31372): #41     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (31372): #42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by alextekartik** [comment]
Sembast only supports json encodable data. I'm not familiar enough with json_serialization to know where the issue is here

**Comment by thejoker101** [comment]
FYI, changing this pat of the annotation allowed the nested objects to be serialized and added to the DB. That's all it took for me.

`@JsonSerializable(explicitToJson: true)`
