### ISSUE TITLE
OS Error: Read-only file system, errno = 30

### ISSUE THREAD

**Issue by egorikem** [tekartik/sembast.dart#55]
Just following along the "tutorial" setup, and this happens. 
### Code
```
void initDb() async {
    store = StoreRef.main();
    db = await databaseFactoryIo.openDatabase(dbPath, version: 1);
}
```
### Result 
```
E/flutter (25210): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot create file, path = '/sample.db' (OS Error: Read-only file system, errno = 30)
E/flutter (25210): #0      _wrap.<anonymous closure> (package:sembast/src/io/file_system_io.dart:102:7)
E/flutter (25210): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (25210): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (25210): #3      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
E/flutter (25210): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
E/flutter (25210): #5      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
E/flutter (25210): #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (25210): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (25210): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (25210): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (25210): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (25210): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (25210): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (25210): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
### Manifest
Manifest looks ok to me:
```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**Comment by egorikem** [comment]
Ok then, the solution has been found. However I do believe that the missing line absolutely shall be added to the tutorial

```
store = StoreRef.main();
final appDocDir = await getApplicationDocumentsDirectory();
db = await databaseFactoryIo.openDatabase(join(appDocDir.path, dbPath), version: 1);
```

**Comment by alextekartik** [comment]
You were trying to open a database (a file) at the root of the file system on which you don't have access (like any other file).

Indeed sembast had no specific flutter information, I added a section here:

https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/open.md#flutter
